language: java

jdk:
  - openjdk11

services:
  - mysql

before_install:
  - sudo mysql -e "UPDATE mysql.user SET authentication_string=PASSWORD('root') WHERE User='root';"
  - sudo service mysql restart

before_script:
  - sudo mysql -u root -e "CREATE DATABASE IF NOT EXISTS criptop2p;"

addons:
  sonarcloud:
    organization: "ggoffredo-jcvincenti"

script:
  - ./gradlew jacocoTestReport sonarqube

# safelist
branches:
  only:
    - main