language: java

jdk:
  - openjdk11

services:
  - postgresql

before_install:
#  - sudo mysql -e "UPDATE mysql.user SET authentication_string=PASSWORD('root') WHERE User='root';"
  - psql -c 'create database criptop2p;' -U postgres
#  - sudo service mysql restart

addons:
  sonarcloud:
    organization: "ggoffredo-jcvincenti"

script:
  - ./gradlew jacocoTestReport sonarqube

# safelist
branches:
  only:
    - main