language: java
jdk:
  - openjdk11
before_install:
  – chmod +x gradlew
addons:
  sonarcloud:
    organization: "ggoffredo-jcvincenti"
script:
  - ./gradlew sonarqube
# safelist
branches:
  only:
    - main