version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/openjdk:11.0.8
      - image: cimg/postgres:9.4
      - image: cimg/python:3.7.4
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      # - run: psql -c 'create database criptop2p;' -U postgres
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew jacocoTestReport sonarqube
      - sonarcloud/scan
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: sonarcloud