version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/postgres:9.4
      - image: circleci/python:3.7.4
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: psql -c 'create database criptop2p;' -U postgres
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew jacocoTestReport sonarqube
      - sonarcloud/scan
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: SonarCloud